version: '3.9'

services:
  mongo:
    image: mongo
    volumes:
      - /data/mongo
    healthcheck:
        interval: 30s
        timeout: 10s
        retries: 5

  videoapi:
    image: amexapiv1
    restart: always
    ports:
      - 4000:4000
    volumes:
      - /data/amex
    depends_on:
      - mongo
