version: '3.9'

services:
  mongo:
    image: mongo
    volumes:
      - /data/mongo
    healthcheck:
        interval: 30s
        timeout: 10s
        retries: 5
    networks:
      - amexnetwork
  video-app:
    image: videoapp
    build:
      context: ./
      dockerfile: dockerfile
    depends_on:
      - mongo
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 15
        window: 50s
    ports:
       #- 8060-8070:7070
        - 3001:3001
    volumes:
      - /data/compose-app

    networks:
      - amexnetwork
  videoapi:
    image: amexapi
    restart: always
    ports:
      - 4000:4000
    volumes:
      - /data/amex
    networks:
      - amexnetwork


 ### put all the networks here
networks:
  amexnetwork:
      external: true
